# Generated by Django 3.1.5 on 2021-01-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_productexistingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productexistingmodel',
            name='ProductUnitsWanted',
        ),
        migrations.AlterField(
            model_name='productexistingmodel',
            name='ProductPicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
