# Generated by Django 3.1.5 on 2021-01-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210130_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='productexistingmodel',
            name='ProductID',
            field=models.CharField(max_length=50, null=True, verbose_name='ПродуктID'),
        ),
        migrations.AlterField(
            model_name='productexistingmodel',
            name='ProductName',
            field=models.CharField(max_length=50, null=True, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='productexistingmodel',
            name='ProductPricePer',
            field=models.CharField(max_length=50, null=True, verbose_name='Цена продукта за штуку'),
        ),
    ]
