# Generated by Django 3.1.5 on 2021-01-31 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20210131_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductExistingModel',
            new_name='Fish',
        ),
    ]
