# Generated by Django 3.1.5 on 2021-01-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20210131_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbuymodel',
            name='ProductName',
            field=models.CharField(max_length=50, null=True, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='productbuymodel',
            name='ProductPicture',
            field=models.CharField(max_length=50, null=True, verbose_name='Ссылка на картинку продукта'),
        ),
        migrations.AlterField(
            model_name='productbuymodel',
            name='ProductPricePer',
            field=models.CharField(max_length=50, null=True, verbose_name='Цена продукта за штуку'),
        ),
        migrations.AlterField(
            model_name='productbuymodel',
            name='ProductUnitsWanted',
            field=models.CharField(max_length=50, null=True, verbose_name='ПродуктID'),
        ),
    ]
