# Generated by Django 3.1.5 on 2021-01-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20210131_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbuymodel',
            name='ProductID',
            field=models.CharField(max_length=50, null=True, verbose_name='ПродуктID'),
        ),
        migrations.AlterField(
            model_name='productbuymodel',
            name='ProductUnitsWanted',
            field=models.CharField(max_length=50, null=True, verbose_name='Количество покуптаель хочет купить'),
        ),
    ]
