# Generated by Django 3.1.2 on 2021-02-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20210131_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('ProductName', models.CharField(max_length=50, null=True, verbose_name='Название продукта')),
                ('ProductDescription', models.CharField(max_length=100, null=True, verbose_name='Описание товара')),
                ('ProductPrice', models.CharField(max_length=50, null=True, verbose_name='Цена')),
                ('ProductID', models.CharField(max_length=50, null=True, verbose_name='ProductID')),
            ],
        ),
        migrations.DeleteModel(
            name='Fish',
        ),
        migrations.DeleteModel(
            name='ProductBuyModel',
        ),
    ]
