# Generated by Django 3.1.2 on 2021-02-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_fishproduct_productrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShrimpProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('ProductName', models.CharField(max_length=35, null=True, verbose_name='Название продукта')),
                ('ProductDescription', models.CharField(max_length=35, null=True, verbose_name='Описание товара')),
                ('ProductRating', models.CharField(max_length=50, null=True, verbose_name='Рейтинг')),
                ('ProductPrice', models.CharField(max_length=50, null=True, verbose_name='Цена')),
                ('ProductID', models.CharField(max_length=50, null=True, verbose_name='ProductID')),
            ],
        ),
        migrations.AlterField(
            model_name='fishproduct',
            name='ProductDescription',
            field=models.CharField(max_length=35, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='fishproduct',
            name='ProductName',
            field=models.CharField(max_length=35, null=True, verbose_name='Название продукта'),
        ),
    ]
