# Generated by Django 3.1.2 on 2021-02-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20210203_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishproduct',
            name='ProductDescription2',
            field=models.CharField(max_length=35, null=True, verbose_name='Описание товара'),
        ),
    ]
