# Generated by Django 3.1.2 on 2021-02-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_shrimpproduct_productdescription2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PictureURL', models.CharField(max_length=25, null=True, verbose_name='URL картинки')),
                ('ProductCount', models.CharField(max_length=25, null=True, verbose_name='Колличество')),
                ('ProductName', models.CharField(max_length=25, null=True, verbose_name='Название товара')),
                ('ProductPrice', models.CharField(max_length=25, null=True, verbose_name='Цена за кг')),
            ],
        ),
        migrations.AlterField(
            model_name='fishproduct',
            name='ProductName',
            field=models.CharField(max_length=25, null=True, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='shrimpproduct',
            name='ProductName',
            field=models.CharField(max_length=25, null=True, verbose_name='Название продукта'),
        ),
    ]
