# Generated by Django 3.1.2 on 2021-02-05 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0013_auto_20210204_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='ProductID',
            field=models.CharField(max_length=50, null=True, verbose_name='ProductID'),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
