# Generated by Django 3.1.2 on 2021-02-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20210205_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='NikitaProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductNikita', models.CharField(max_length=25, null=True, verbose_name='Характеристики никиты')),
            ],
        ),
    ]
