# Generated by Django 3.1.2 on 2021-02-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_nikitaproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='nikitaproduct',
            name='Name',
            field=models.CharField(max_length=25, null=True, verbose_name='Мое имя'),
        ),
    ]
