# Generated by Django 3.1.2 on 2021-02-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_nikitaproduct_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoNikita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NikitaName', models.CharField(max_length=25, null=True, verbose_name='URL картинки')),
                ('NikitaProfil', models.CharField(max_length=25, null=True, verbose_name='URL картинки')),
            ],
        ),
        migrations.DeleteModel(
            name='NikitaProduct',
        ),
    ]
