# Generated by Django 3.1.2 on 2021-02-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_auto_20210210_1309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoNikita',
        ),
        migrations.DeleteModel(
            name='ShrimpProduct',
        ),
        migrations.AddField(
            model_name='fishproduct',
            name='ProductType',
            field=models.CharField(max_length=25, null=True, verbose_name='Тип продукта'),
        ),
    ]
