# Generated by Django 3.1.7 on 2021-03-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_clientinfo_surnameclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input1', models.CharField(max_length=25, null=True, verbose_name='Сообщение 1')),
                ('Key', models.CharField(max_length=25, null=True, verbose_name='Кому')),
            ],
        ),
    ]
