# Generated by Django 3.1.7 on 2021-03-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='Key',
        ),
    ]
