# Generated by Django 3.1.7 on 2021-03-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_remove_test_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='ClientAddress',
            field=models.CharField(max_length=100, null=True, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='ClientEmail',
            field=models.CharField(max_length=50, null=True, verbose_name='Е-майл'),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='ClientPhone',
            field=models.CharField(max_length=25, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='DeliveryMethod',
            field=models.CharField(max_length=25, null=True, verbose_name='Способ доставки'),
        ),
    ]
