# Generated by Django 3.1.7 on 2021-03-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_clientinfo_clientproductname'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='ClientProductCount',
            field=models.CharField(max_length=100, null=True, verbose_name='Колличество заказанных продукты'),
        ),
    ]
