# Generated by Django 3.1.7 on 2021-03-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0028_clientinfo_prname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='ClientProductCount',
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='ClientProductName',
        ),
    ]
