# Generated by Django 3.1.7 on 2021-03-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0032_auto_20210315_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addproduct',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AlterModelOptions(
            name='clientinfo',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Поступление заказов'},
        ),
        migrations.AlterModelOptions(
            name='fishproduct',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
