# Generated by Django 3.1.7 on 2021-03-15 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0033_auto_20210315_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='dateDone',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 20, 59, 10, 590198), verbose_name='Дата выполнения'),
        ),
    ]
