# Generated by Django 3.1.7 on 2021-03-16 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0034_clientinfo_datedone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='orderId',
            field=models.CharField(max_length=50, null=True, verbose_name='OrderId'),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='dateDone',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 16, 13, 49, 360267), verbose_name='Дата выполнения'),
        ),
    ]
