# Generated by Django 3.1.7 on 2021-03-16 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0035_auto_20210316_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='dateDone',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 16, 17, 44, 662263), verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='orderId',
            field=models.CharField(max_length=100, null=True, verbose_name='OrderId'),
        ),
    ]
