# Generated by Django 3.1.7 on 2021-03-17 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0036_auto_20210316_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='dateDone',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 12, 45, 38, 444329), verbose_name='Дата выполнения'),
        ),
    ]
