# Generated by Django 3.1.7 on 2021-03-17 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0037_auto_20210317_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='dateDone',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 13, 25, 21, 808593), verbose_name='Дата выполнения'),
        ),
    ]
