# Generated by Django 3.1.7 on 2021-03-17 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0039_auto_20210317_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='dateDone',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 13, 30, 24, 641598), verbose_name='Дата выполнения'),
        ),
    ]
