# Generated by Django 3.1.7 on 2021-03-17 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0040_auto_20210317_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='dateDone',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 13, 31, 51, 782593), verbose_name='Дата выполнения'),
        ),
    ]
