# Generated by Django 3.1.7 on 2021-03-17 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0041_auto_20210317_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='dateDone',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 13, 32, 23, 747592), verbose_name='Дата выполнения'),
        ),
    ]
