# Generated by Django 3.1.7 on 2021-03-17 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0042_auto_20210317_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='dateDone',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 13, 33, 45, 432593), verbose_name='Дата выполнения'),
        ),
    ]
