# Generated by Django 3.1.7 on 2021-03-17 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0044_auto_20210317_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='dateDone',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 13, 46, 4, 542598), verbose_name='Дата выполнения'),
        ),
    ]
