# Generated by Django 3.1.7 on 2021-03-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0052_auto_20210317_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='statusOrder',
            field=models.CharField(max_length=25, null=True, verbose_name='Статус заказа'),
        ),
    ]
