# Generated by Django 3.1.7 on 2021-03-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0053_clientinfo_statusorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='statusOrder',
            field=models.CharField(default='На рассмотрении', max_length=25, verbose_name='Статус заказа'),
        ),
    ]
