# Generated by Django 3.1.7 on 2021-03-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0054_auto_20210317_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='statusOrder',
            field=models.CharField(max_length=25, verbose_name='Статус заказа'),
        ),
    ]
