# Generated by Django 3.1.7 on 2021-03-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0056_auto_20210317_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='statusColor',
            field=models.CharField(default='colorfirst', max_length=25, verbose_name='Цвет статуса заказа'),
        ),
    ]
