# Generated by Django 3.1.7 on 2021-03-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0057_clientinfo_statuscolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishproduct',
            name='ProductSize1',
            field=models.CharField(default='', max_length=25, verbose_name='Размер 1'),
        ),
        migrations.AddField(
            model_name='fishproduct',
            name='ProductSize2',
            field=models.CharField(default='', max_length=25, verbose_name='Размер 2'),
        ),
        migrations.AddField(
            model_name='fishproduct',
            name='ProductSize3',
            field=models.CharField(default='', max_length=25, verbose_name='Размер 3'),
        ),
        migrations.AddField(
            model_name='fishproduct',
            name='ProductSize4',
            field=models.CharField(default='', max_length=25, verbose_name='Размер 4'),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='orderId',
            field=models.CharField(max_length=100, null=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='fishproduct',
            name='ProductRating',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Рейтинг'),
        ),
    ]
