# Generated by Django 3.1.7 on 2021-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0058_auto_20210323_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishproduct',
            name='ProductRating',
            field=models.CharField(max_length=50, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='fishproduct',
            name='ProductSize1',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Размер 1'),
        ),
        migrations.AlterField(
            model_name='fishproduct',
            name='ProductSize2',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Размер 2'),
        ),
        migrations.AlterField(
            model_name='fishproduct',
            name='ProductSize3',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Размер 3'),
        ),
        migrations.AlterField(
            model_name='fishproduct',
            name='ProductSize4',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Размер 4'),
        ),
    ]
